"""
Hyperparameters etc.
"""

TICKERS = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "ADAUSDT", "AVAXUSDT", "DOGEUSDT", "DOTUSDT",
           "LINKUSDT", "TRXUSDT", "LTCUSDT", "SHIBUSDT", "ICPUSDT", "BCHUSDT"]
