name: "A2C-MLP-Baseline"
algo: "A2C"

# SB3 hyperparameters
learning_rate: 0.0007
n_steps: 5
gamma: 0.99           # Discount factor (how important is the future)
gae_lambda: 1.0
ent_coef: 0.01        # Entropy coefficient (how much agent should explore)
vf_coef: 0.5          # Value function coefficient
max_grad_norm: 0.5
rms_prop_eps: 1e-5

# Policy Network
policy_type: "MlpPolicy"
policy_kwargs:
  net_arch: [64, 64]  # two 64-neuron hidden layers
